#!/bin/bash

if [ -n "$GOPATH" ]; then
  echo "Building rack!"
  COMMIT=$(git rev-parse --verify HEAD)
  echo -e "package util\n\nvar Commit = \"$COMMIT\"" > util/commit.go
  go build -o $GOPATH/bin/rack
else
  echo '$GOPATH must be defined. Do you have go setup?'
fi
