#!/bin/bash

# Load our library functions
SCRIPT_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
source "${SCRIPT_DIR}/lib.sh"

build() {
  if [ -n "$GOPATH" ]; then
    echo "Building rack!"

    RACKBUILD=${1:-${GOPATH}/bin/rack}

    get_commit
    get_version

    # Check the go version
    EQ="="
    # If we are golang <= 1.4, ' ' for EQ ... else '='
    regex="(go[0-1].[0-4](?![0-9]))"
    if [[ `go version` =~ $regex ]]; then
        EQ=" "
    fi

    LDFLAGS="-X github.com/rackspace/rack/util.Commit${EQ}${COMMIT} \
             -X github.com/rackspace/rack/util.Version${EQ}${VERSION}"
    CGO_ENABLED=0 go build -a -installsuffix cgo -ldflags "${LDFLAGS}" -o "${RACKBUILD}"
    return $?
  else
    echo "\$GOPATH must be defined. Do you have go setup?"
    return 1
  fi
}

build "$1"
