#!/bin/bash

SCRIPT_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )
source $SCRIPT_DIR/lib.sh

build() {
  if [ -n "$GOPATH" ]; then
    echo "Building rack!"

    if [ -z "$RACKBUILD" ]; then
        RACKBUILD=$GOPATH/bin/rack
    fi

    get_commit
    get_version

    COMMIT=$(git rev-parse --verify HEAD)
    LDFLAGS="-X github.com/rackspace/rack/util.Commit=${COMMIT} \
             -X github.com/rackspace/rack/util.Version=${VERSION}"
    go build  -ldflags "$LDFLAGS" -o $RACKBUILD
    return $?
  else
    echo '$GOPATH must be defined. Do you have go setup?'
    return 1
  fi
}

build
