#!/bin/bash

set -euo pipefail

ROOT=$(cd $(dirname $0)/.. && pwd)

TARGET=${1:-staging}

case "${TARGET}" in
  staging)
    CONTENT_STORE_URL=http://staging.developer.rackspace.com:8000
    ;;
  production)
    CONTENT_STORE_URL=https://developer.rackspace.com:9000
    ;;
  http*)
    CONTENT_STORE_URL=${TARGET}
    ;;
  *)
    echo "Usage: ${0} <environment|http://...>"
    exit 1
    ;;
esac

[ -z "${CONTENT_STORE_APIKEY:-}" ] && {
  echo "No API key set!" >&2
  echo "export CONTENT_STORE_APIKEY=\"...\""
  exit 1
}

echo "Submitting metadata envelopes to ${CONTENT_STORE_URL}."

exec docker run --rm \
  -e CONTENT_STORE_URL=${CONTENT_STORE_URL} \
  -e CONTENT_STORE_APIKEY=${CONTENT_STORE_APIKEY} \
  -e TRAVIS_PULL_REQUEST="false" \
  -v ${ROOT}/docs:/usr/content-repo \
  quay.io/deconst/preparer-sphinx
