#!/bin/bash
set -euo pipefail

#
# Helper function to do replace; this should work across operating systems
#

function update {
  TMP_FILE=$(mktemp -d 2>/dev/null || mktemp -d -t "$1")
  sed -e "$2" "$3" > "$TMP_FILE"
  chmod 0644 "$TMP_FILE"
  mv -f "$TMP_FILE" "$3"
}

NEW_VERSION=${1:-}
REMOTE="release"
REMOTE_URL="git@github.com:rackspace/rack.git"
DOCS_INDEX_FILE="docs/index.rst"
DOCS_CONFIGURATION_FILE="docs/configuration.rst"
BRANCH=$(git rev-parse --abbrev-ref HEAD)

echo "Releasing new version: ${NEW_VERSION}"

#
# First confirm we're operating on the master branch
#

if [ "$BRANCH" != "master" ]; then
  echo "Must release from master branch"
  exit 1
fi

#
# Confirm that we have a remote named "Release"
#

git remote show ${REMOTE} &> /dev/null

rc=$?

if [[ $rc != 0 ]]; then
  echo "Remote \"${REMOTE}\" not found. Exiting."
  exit 2
fi

#
# Now confirm that we've got the proper remote URL
#

REMOTE_ACTUAL_URL=$(git remote show release | grep Push | cut -d ":" -f2-)

if [ "$REMOTE_URL" != "$REMOTE_ACTUAL_URL" ]; then
  echo -e "Remote \"${REMOTE}\" PUSH url incorrect.\nShould be ${REMOTE_URL}. Exiting."
  exit 3
fi

#
# Confirm our workspace is clean
#

set +e
git diff --exit-code | /dev/null
if [ $? != 0 ]; then
  echo "Workspace is not clean. Exiting"
  exit 4
fi
set -e

#
# Ensure we're in sync with release remote
#

git fetch $REMOTE
SYNC_STATUS=$(git rev-list master...${REMOTE}/master)

if [ -n "$SYNC_STATUS" ]; then
  echo "Master is not in sync with release remote. Exiting."
  exit 5
fi

#
# Update the docs index paths
#

update ./index.rst-version "s#rackcdn\.com/[0-9a-zA-Z.-]*/#rackcdn\.com/$NEW_VERSION/#g" $DOCS_INDEX_FILE

#
# Update the docs configuration paths
#

update ./configuration.rst-version "s#rackcdn\.com/[0-9a-zA-Z.-]*/#rackcdn\.com/$NEW_VERSION/#g" $DOCS_CONFIGURATION_FILE

#
# Commit and push the code changes
#

git commit -am "Version ${NEW_VERSION}"
git tag "${NEW_VERSION}"
git push ${REMOTE} master
git push ${REMOTE} --tags

echo "${NEW_VERSION} successfully released"
